### ISSUE TITLE
Update dependencies version

### ISSUE THREAD

**Issue by igorgoncalves** [rockneurotiko/awesome-bot#3]
Some dependencies like "telegram-bot" are in a old version, and dont work with other updateds libs like "hyper"

**Comment by rockneurotiko** [comment]
I should write on the Readme that I'm not supporting this library anymore, anybody are free to do PRs and I'll review them and merge if they'r ok, but I don't have time 😢 

Sorry!

**Comment by berkus** [comment]
I started on the port to new, async version of telegram-bot (0.6.1 atm).

**Comment by berkus** [comment]
See also #7
